### ISSUE TITLE
wkhtmltopdf.exe dependency

### ISSUE THREAD

**Issue by cartfisk** [nickrussler/eml-to-pdf-converter#1]
Currently trying to see if I can tweak to use the OS X version of wkhtmltopdf as everything else seems to be OS X compatible and this single dependency is preventing the program from running on Mac.

**Comment by nickrussler** [comment]
This should not be a problem at all, just build it with `gradlew shadowJar` or use the binarie from the [release](https://github.com/nickrussler/eml-to-pdf-converter/releases/download/1.0.0/emailconverter.jar) and install [wkhtmltopdf for macos](http://wkhtmltopdf.org/downloads.html). Just add the wkhtmltopdf binary to PATH and it should work.

**Comment by cartfisk** [comment]
Okay cool, some of the gradle tests were giving me errors related to wkhtmltopdf but it was unrelated. Got the jar up and running thank you!

**Comment by nickrussler** [comment]
I just removed the crash reporting code and parameter (which was dead code anyways). So i recommend you to use the new release (or code).
