### ISSUE TITLE
How to use this as Java library

### ISSUE THREAD

**Issue by huchenhai** [nickrussler/eml-to-pdf-converter#10]
Hi, I'm writing a web service to convert eml to pdf, how can i use it as a Java class?

**Comment by nickrussler** [comment]
You can use the jar and call [MimeMessageConverter.convertToPdf](https://github.com/nickrussler/eml-to-pdf-converter/blob/master/src/main/java/cli/Main.java#L119).

**Comment by huchenhai** [comment]
Thank you so much , sorry  I forgot to ask, is this able to support multi threading?

**Comment by nickrussler** [comment]
Yes, I did not test explicitly, but everything should be multi thread safe.
