### ISSUE TITLE
Difficulty passing [eml-filename]

### ISSUE THREAD

**Issue by horusofoz** [nickrussler/eml-to-pdf-converter#12]
I'm trying to call EMLtoPDFConverter from PowerShell to integrate into an existing workflow. I've tried passing the EML's file path as per below but in both cases the App launches it's GUI but nothing happens.

```powershell
Start-Process "C:\Program Files (x86)\EMLtoPDFConverter\EmailConverter.exe" "C:\Temp\Attachments\tempEmail.eml"

Start-Process "C:\Program Files (x86)\EMLtoPDFConverter\EmailConverter.exe"-ArgumentList "C:\Temp\Attachments\tempEmail.eml"
```

#Running "C:\Program Files (x86)\EMLtoPDFConverter\EmailConverter.exe" "C:\Temp\Attachments\tempEmail.eml" in CMD also causes the app's GUI to launch.

Can you please advise where I'm messing up in my syntax?

Many thanks :)

**Comment by Bennytl** [comment]
A bit late, but i had same problem, took a while before i noticed the obvious/other exe file : EMaiLConverterConsole.exe
