### ISSUE TITLE
Feature Request:Select Timezone for Dates/Times in resultant PDF

### ISSUE THREAD

**Issue by Ferretaa** [nickrussler/eml-to-pdf-converter#18]
Hi, 
Would it be possible to configure the resultant PDF to contain the dates/times in a different timezone? Currently when they are converted they are displayed in UTC.

**Comment by nickrussler** [comment]
This one is a bit tricky, since the content of the date header is not always well-formed. In this case a fallback onto the raw value could be made, but then the result would be inconsistent.

**Comment by nickrussler** [comment]
Dates are now formatted with the default locale. You can change it, e.g. by passing the VM argument `-Duser.language=en-US` similar to setting the timezone e.g. `-Duser.timezone="Asia/Kolkata"`.
