### ISSUE TITLE
wkhtmltopdf, 0.12.6, Warning: Blocked access to file

### ISSUE THREAD

**Issue by patrickuhlmann** [nickrussler/eml-to-pdf-converter#20]
I am running an updated Archlinux installation. When I convert an email I see a grey background frame at the top of the generated PDF. It used to work.

I executed it with the -d flag and found the following message:
Warning: Blocked access to file /tmp/emailtopdf5168555425623546812.html

A research indicates that a command line parameter is needed in order to embed local html files for the latest version of wkhtmltopdf:
https://stackoverflow.com/questions/62315246/wkhtmltopdf-0-12-6-warning-blocked-access-to-file

Example files:
[Test.zip](https://github.com/nickrussler/eml-to-pdf-converter/files/4794982/Test.zip)

**Comment by patrickuhlmann** [comment]
I quickly verified, adding the parameter "--enable-local-file-access" in the MimeMessageConverter.java makes it work again:
https://github.com/patrickuhlmann/eml-to-pdf-converter/commit/ab6de9d7e80e557f08fd71134e789ad685e8ae3c

**Comment by nickrussler** [comment]
@patrickuhlmann Thanks for the report and for even providing the solution. If you could send a pr, that would be amazing. Thanks!
