### ISSUE TITLE
Could not run program (wkhtmltopdf) on my Mac Os (Sierra , version- 10.12.6)

### ISSUE THREAD

**Issue by inDiscover** [nickrussler/eml-to-pdf-converter#22]
The error is as below,

`Cannot run program "wkhtmltopdf": error=2, No such file or directory`

In my research what I found is that the above error is Mac related because my java program cannot run the executable(wkhtmltopdf) from the path  (**/usr/local/bin**) where this executable (wkhtmltopdf) installed on my Mac. 

My Java program returns only below PATHs, So Java can run the executable only from any of these paths.

**/usr/bin , /usr/sbin , /sbin**

But My Mac OS does not permit me to do any operations on these PATH - **/usr/bin , /usr/sbin , /sbin**  as part of security.

So I had to provide full path to the executable (like **/usr/local/bin/wkhtmltopdf** instead of just **wkhtmltopdf**) so that my  Java program can run the executable without any errors.

And ,in MimeMessageConverter.java , I could see that there is no option to provide full path to the executable. (For example : **/usr/local/bin/wkhtmltopdf** instead of just **wkhtmltopdf** , which is currently hardcoded). So I strongly believe that this option (ie , to provide full path to the executable) should be available in MimeMessageConverter.java  so that any user whose Mac OS will not permit to do any operations on these PATH - **/usr/bin , /usr/sbin , /sbin** can execute a java program to run the executable without any error.  Otherwise (If any Mac OS permit us to do any operations on these PATH) we could have been copied the executable to any of these PATH so that any Java program can run that executable without any errors.

**Comment by nickrussler** [comment]
Maybe you can create a symlink next to the jar to the executable?

**Comment by inDiscover** [comment]
You mean to create a symlink from any of these PATHS - **/usr/bin , /usr/sbin , /sbin** to the executable? . If so , then I should create a file inside any of these PATH right?. But my Mac OS won't permit any operations inside these folder. If I am wrong then can you please explain me what exactly you are trying to say?

**Comment by Ferretaa** [comment]
I think what Nick is trying to say is if you create the symlink in /usr/bin it will enable the app to be executed as if it was actually in that location. 
Details on how to setup the symlink below:
How to Create and Use Symbolic Links (aka Symlinks) on a Mac: https://www.howtogeek.com/297721/how-to-create-and-use-symbolic-links-aka-symlinks-on-a-mac/

**Comment by inDiscover** [comment]
@Ferretaa  , thats what I mentioned above that my mac OS does not permit me to do any operation on those PATH. Please find the below screenshots.

Screenshot 1 : Here you can see the **wkhtmltopdf** .

![Screen Shot 2020-06-27 at 9 00 56 AM](https://user-images.githubusercontent.com/12743038/85913852-f7f54a00-b855-11ea-9e29-6e4d94e21672.png)

Screenshot 2 : Here you can see the command I executed to create a symlink. Please let me know if anything wrong in the command I used to create a symlink.

![Screen Shot 2020-06-27 at 9 04 16 AM](https://user-images.githubusercontent.com/12743038/85913868-23783480-b856-11ea-8a5a-928dfd4d2c97.png)

**Comment by nickrussler** [comment]
Maybe creating a symlink in the same directory as the jar would work?
