### ISSUE TITLE
Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown; And other error messages

### ISSUE THREAD

**Issue by inDiscover** [nickrussler/eml-to-pdf-converter#23]
I download email (in .eml format) from my Outlook and then I am trying to convert it to PDF.

1. Error: Failed to load about:blank, with network status code 301 and http status code 0 - Protocol "about" is unknown.
2. Exit with code 1 due to network error: ProtocolUnknownError.
3. Exception in thread "main" com.sun.mail.util.FolderClosedIOException.

I am getting these errors while converting to pdf. But only when the flag "hideHeader" set to false (means I do need header details as well in my pdf). When the flag set to true then no error messages are showing.

I am attaching a sample eml file which I used to convert to pdf. Note that pdf generated successfully but pdf does not contain any header info (like From , To , Subject , Date etc.) . But , at the same , I am getting above mentioned errors.

Below are the arguments passed in,
**`MimeMessageConverter.convertToPdf(emlPath, pdfPath, false, true, attachmentPath, extParams);`**

[Test_file1593397582267.eml.pdf](https://github.com/nickrussler/eml-to-pdf-converter/files/4843444/Test_file1593397582267.eml.pdf)

Since I am not able to attach .eml file , I just renamed it to **.pdf**. But this can be renamed to **.eml** for any testing purpose.

**Comment by nickrussler** [comment]
Conversion works for, was probably fixed with the wkhtmltopdf flag
