### ISSUE TITLE
Resource header.html could not found while executing the jar from a third party server.

### ISSUE THREAD

**Issue by inDiscover** [nickrussler/eml-to-pdf-converter#24]
I tried to execute this jar(eml-to-pdf-converter) from my Application Server(ColdFusion). But ColdFusion throwing an error saying that the resource header.html could not found.

In this eml-to-pdf-converter library I could see that Resources.getResource("header.html") in MimeMessageConverter.Java. 

I found something in Stackoverflow (https://stackoverflow.com/questions/23985971/referencing-java-resource-files-from-coldfusion) which says to use getResourceAsStream. So , I was thinking that the java file (MimeMessageConverter.Java.) needs to be modified to use getResourceAsStream instead of getResource to fix this issue.

**Comment by nickrussler** [comment]
If you integrated the jar and call the main method directly from your code, maybe you could instead run java and use the CLI, see https://www.baeldung.com/run-shell-command-in-java.

**Comment by inDiscover** [comment]
I am not calling main method directly. Instead I followed the below steps.

1.Created a new project (with a single class say       EmlToPDFConverter.java) in eclipse. This project uses your library(eml-to-pdf converter).
2.Created a jar.
3.Deployed the newly created jar from step 2 on ColdFusion server(3rd party).
4.From ColdFusion I created an object to my class (step 1 , EmlToPDFConverter). When I dump this object from ColdFusion I am able to see methods defined in the object. But while executing a wrapper method in my class , which internally calling MimeMessageConverter.convertToPdf , I am getting below two errors,

Error 1 : java.lang.IllegalArgumentException: resource header.html
not found.

Error 2 : java.lang.ClassCastException: class com.sun.mail.handlers.multipart_mixed cannot be cast to class javax.activation.DataContentHandler (com.sun.mail.handlers.multipart_mixed is in unnamed module of loader coldfusion.bootstrap.BootstrapClassLoader @474619d9; javax.activation.DataContentHandler is in unnamed module of loader coldfusion.runtime.java.JavaDynamicClassLoader @39223fbc)

**Comment by nickrussler** [comment]
How does this EmlToPDFConverter.java use eml-to-pdf converter?

**Comment by inDiscover** [comment]
EmlToPDFConverter.java uses your library as an external dependency and hence to call MimeMessageConverter.convertToPdf .
Regarding the quick fix you mentioned - You mean like this java -jar emailconverter-2.0.0-all.jar example.eml? If this is not correct what you are trying to say then please explain what you actually mean by "just try to call the CLI on the jar by spawning a java process."

**Comment by nickrussler** [comment]
@inDiscover I pushed a fix, please let me know if it worked
