### ISSUE TITLE
Accented character corrupted (encoding)

### ISSUE THREAD

**Issue by mklodner** [nickrussler/eml-to-pdf-converter#25]
Hi, I tried to convert some emls using EmailConverterConsole.exe but sometimes the accented characters (ěščř...) got corrupted i nthe result pdf. Is there any way to specify the encoding? Thanks. Michal K.

**Comment by nickrussler** [comment]
Please provide an example eml file

**Comment by mklodner** [comment]
Hi Nick, very happy to do that but the mail is not or the public. Can I send it directly to you? Thanks a lot! Michal K.

**Comment by nickrussler** [comment]
Sure please send it to nick.russler@gmail.com

**Comment by nickrussler** [comment]
The problems comes from a wrongly declared charset within the html in the email:

`<meta http-equiv=Content-Type content="text/html; charset=iso-8859-2">`

But the email headers are

```
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable
```

When opening the html content with a browser it also shows the corrupted characters and when changing it in the html to UTF-8 everything works.

Therefore the only fix I can think of is comparing the email header charset vs the html declared charset and when having a mismatch sniffing it and then enforcing the sniffed charset in the html.

**Comment by mklodner** [comment]
Thanks @nickrussler! It really was the issue of different charsets. After changing both charsets to UTF-8, it works.

**Comment by nickrussler** [comment]
@mklodner In the new version, the above fix should also fix the conversation in case the html declares a wrong charset.
