### ISSUE TITLE
Garbled text (encoding)

### ISSUE THREAD

**Issue by SteffenL** [nickrussler/eml-to-pdf-converter#26]
I tried to use `emailconverter-2.2.1-all.jar` on Linux with eml that embeds HTML that specifies UTF-8 charset everywhere and no other charsets. This produces partially garbled text in my case; however, using version 2.1.1 with the same document works fine for me.

I can share the eml but not in public.

## Results

2.2.1
![image](https://user-images.githubusercontent.com/1543854/94439930-01d37400-01dc-11eb-8a96-950138bca350.png)

2.1.1
![image](https://user-images.githubusercontent.com/1543854/94440079-29c2d780-01dc-11eb-8951-67527abea6c5.png)

**Comment by nickrussler** [comment]
Please send it to nick.russler@gmail.com

**Comment by SteffenL** [comment]
Sent.

**Comment by nickrussler** [comment]
@SteffenL Can you check if it works again with 2.2.2? I don't have the fonts locally I suspect

**Comment by SteffenL** [comment]
Version 2.2.2 works as expected. Thank you for the swift fix!
