### ISSUE TITLE
Feature Request: Add Support for Outlook *.msg files

### ISSUE THREAD

**Issue by spongioblast** [nickrussler/eml-to-pdf-converter#5]
It would be great if you could add support for outlook *.msg files:
[Oulook msg file example](https://github.com/nickrussler/eml-to-pdf-converter/files/243536/SubjectofTestemail.zip)

**Comment by nickrussler** [comment]
I would recommend to convert the msg file to the eml format. There are [free](https://sourceforge.net/projects/msgviewer/) and [commercial](http://www.independentsoft.de/jmsg/tutorial/convertmsgtomime.html) tools available.

**Comment by nickrussler** [comment]
This could be done with http://www.simplejavamail.org/features.html#section-converting

**Comment by nickrussler** [comment]
Support was added in release 2.3.0
