### ISSUE TITLE
Conversion has problems with german Umlaute

### ISSUE THREAD

**Issue by patrickuhlmann** [nickrussler/eml-to-pdf-converter#6]
I tried the eml-to-pdf-converter with multiple German eml-Files. In some cases the conversion was successful and in some cases the german Umlaut are messed up. 

Here you can find a good and a bad example. I added the generated pdf as well as the original eml-file: https://drive.google.com/open?id=0BwK5xWaaOr4nZm5RVmg4UzhtODg

I used the following command to convert the files:
java -jar emailconverter-2.0.1-all.jar --extract-attachments --extract-attachments-directory ./ $filename

Do you have any idea how this can be fixed this?

**Comment by nickrussler** [comment]
I could not reproduce the issue (see attachment). Can you give me some details on your OS and the wkhtmltopdf version?

[Bad.pdf](https://github.com/nickrussler/eml-to-pdf-converter/files/1289901/Bad.pdf)

**Comment by patrickuhlmann** [comment]
I am using Fedora 26

Kernel: Linux localhost-uhlme 4.12.8-300.fc26.x86_64 #1 SMP Thu Aug 17 15:30:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

wkhtmltopdf: wkhtmltopdf 0.12.3

Which version are you using?

**Comment by patrickuhlmann** [comment]
Which version are you using?

**Comment by nickrussler** [comment]
I produced the pdf on a machine running Windows 10, using wkhtmltopdf 0.12.4 (with patched qt).

**Comment by nickrussler** [comment]
@patrickuhlmann Could you resolve your problem? And if, could you please share how?

**Comment by patrickuhlmann** [comment]
I forked the code and made a quick fix here: https://github.com/patrickuhlmann/eml-to-pdf-converter/commit/94597c23fd4fbfa02e11874ed474caff11e0b107

Basically the problem was the following: The encoding of the mail was iso-8859-1. The class ContentTypeCleaner needed to decode it as QuotedPrintable. However the method doing this was "forcing" UTF-8. I did not fix the detection but added a new parameter charset. That parameter allows me to properly convert my mails.

**Comment by nickrussler** [comment]
Glad you could resolve your issue!

Both eml files you provided specify an UTF-8 encoding. Could you provide me with an exemplary iso-8859-1 encoded eml that caused the problem?

**Comment by patrickuhlmann** [comment]
https://drive.google.com/open?id=17zb586dYvNcrz415k5O-fPQkf4GOBrjx

You find in the archive an eml as well as the pdf file (- bad) that results when I convert it with the original version. I did also attach the pdf file (- correct) that results when I convert it with my patched version (passing the correct encoding).

**Comment by nickrussler** [comment]
Can't reproduce
